# Site settings
title: jangp Blog
header-img: img/home-bg.jpg
email: juancarlosgpelaez@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://http://jgpelaez.github.io/"
twitter_username: jcgpelaez
github_username:  jgpelaez
linkedin_username:  jgpelaez

permalink: /:title/

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/es
    values:
      lang: es
  -
    scope:
      path: _posts/es/pages
    values:
      type: pages
      desc: "Site personnel traitant essentiellement de programmation en Python, Ruby, TeX, R..."
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
      desc: "Personnal website mostly about programming in Python, Ruby, TeX, R..."

  -
    scope:
      path: _posts/es/projects
    values:
      type: projects
  -
    scope:
      path: _posts/en/projects
    values:
      type: projects
