# Site settings
title: Juan Carlos G. Peláez Blog
header-img: img/home-bg.jpg
email: juancarlosgpelaez@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://jgpelaez.github.io/"
twitter_username: jcgpelaez
github_username:  jgpelaez
linkedin_username:  juancarlosgpelaez
disqus_shortname: jgpelaezgithubio

permalink: /:title/

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/es
    values:
      lang: es
  -
    scope:
      path: _posts/es/pages
    values:
      type: pages
      desc: "Sitio personal sobre programaciónm, Java, SOA, WSO2, DevOps..."
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
      desc: "Personnal website mostly about programming, Java, SOA, WSO, DevOps..."

  -
    scope:
      path: _posts/es/projects
    values:
      type: projects
  -
    scope:
      path: _posts/en/projects
    values:
      type: projects
