# Site settings
title: Juan Carlos G. Peláez
header-img: img/home-bg.jpg
email: juancarlosgpelaez@gmail.com
description: "Site about devops, cloud computing and software in general"
baseurl: ""
url: "http://jgpelaez.github.io/"
twitter_username: jcgpelaez
github_username:  jgpelaez
linkedin_username:  juancarlosgpelaez
disqus_shortname: jgpelaezgithubio
header-img: "media/background/oosstende-clouds3.jpg"
exclude: ["node_modules","serve-jekyll*","npm*","Gemfile"]

permalink: /:title/

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/es
    values:
      lang: es
  -
    scope:
      path: _posts/es/pages
    values:
      type: pages
      desc: "Sitio personal sobre la nube, programación, Java, SOA, WSO2, DevOps..."
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
      desc: "Personnal website mostly about the cloud, programming, Java, SOA, WSO, DevOps..."

  -
    scope:
      path: _posts/es/projects
    values:
      type: projects
  -
    scope:
      path: _posts/en/projects
    values:
      type: projects
